### ISSUE TITLE
Incompatible with Guzzle 6?

### ISSUE THREAD

**Issue by sayanb** [zoonman/pixabay-php-api#1]
Hi,

Our application has Unsplash's PHP SDK, which depends on Guzzle 6. Trying to install Pixabay now, but getting this because of Guzzle incompatibility:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for zoonman/pixabay-php-api ^1.0 -> satisfiable by zoonman/pixabay-php-api[1.0.0].
    - Conclusion: remove guzzlehttp/guzzle 6.1.1
    - Conclusion: don't install guzzlehttp/guzzle 6.1.1
    - zoonman/pixabay-php-api 1.0.0 requires guzzlehttp/guzzle ~5.0 -> satisfiable by guzzlehttp/guzzle[5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.1.0, 5.2.0, 5.3.0].
    - Can only install one of: guzzlehttp/guzzle[5.0.0, 6.1.1].
    - Can only install one of: guzzlehttp/guzzle[5.0.1, 6.1.1].
    - Can only install one of: guzzlehttp/guzzle[5.0.2, 6.1.1].
    - Can only install one of: guzzlehttp/guzzle[5.0.3, 6.1.1].
    - Can only install one of: guzzlehttp/guzzle[5.1.0, 6.1.1].
    - Can only install one of: guzzlehttp/guzzle[5.2.0, 6.1.1].
    - Can only install one of: guzzlehttp/guzzle[5.3.0, 6.1.1].
    - Installation request for guzzlehttp/guzzle == 6.1.1.0 -> satisfiable by guzzlehttp/guzzle[6.1.1].

Installation failed, reverting ./composer.json to its original content.

What would be the best way to resolve this?

**Comment by zoonman** [comment]
See version 1.0.1
https://github.com/zoonman/pixabay-php-api/releases/tag/1.0.1
