### ISSUE TITLE
Upgrade to guzzlehttp/guzzle ^7.0

### ISSUE THREAD

**Issue by connecteev** [zoonman/pixabay-php-api#7]
Could we upgrade this package to require the latest version of guzzle, v 7.0.ie "guzzlehttp/guzzle": "^7.0"

I am trying to resolve this issue: https://github.com/composer/composer/issues/9306
and am seeing conflicts because of different minimum required versions of guzzle.

**Comment by joshbmarshall** [comment]
Would be great if the newer guzzle could be used as well

**Comment by connecteev** [comment]
Any update on this?

**Comment by zoonman** [comment]
Please upgrade to 2.0.0
