### ISSUE TITLE
Is this repo abandoned?

### ISSUE THREAD

**Issue by joshbmarshall** [zoonman/pixabay-php-api#9]
Hi I'm using this in my projects and really just need PR #8 merged and a release cut. But doesn't look like anything is happening.
Is this project abandoned, or is it wanting someone to maintain it?

**Comment by joshbmarshall** [comment]
FYI for anyone else coming to this, I'm using https://packagist.org/packages/connecteev/pixabay-php-api now

**Comment by zoonman** [comment]
Please upgrade to 2.0.0
